;;; alt-list.tf 
;;; Variables to hold alts.  Format: <main_alt>_alts=all the alts names
/set aniol_alts=Aniol Ainia Fate Nia Tiffany Aerie Cassiopeia Evengelia Kekoa Teiyla Tindra Tingle Andora Sorella Caylin Isadora Andromeda Nenea Enelya Vynorminia
/set bert_alts=Bertrand Droque Kansas Matanca Maxy Nimble Nit
/set best_alts=Healie Severon Best Veaga Tunn Mochi Woga Pguin Fizoray Rol
/set brahma_alts=Brahma Rama Benevolio Furi Rathe Razorsedge Wrathe Roon Brutalis
/set chog_alts=Chogall Bemoth Antharax Elan Neverind Ervindel LAN
/set crunge_alts=Crunge Ebin Pohi Gravboy Gravman Rraf Qwik Doozer Gravman
/set foiler_alts=Foiler Boss Innex Moshington Wombat Demonbow
/set gene_alts=Lycee Miko Tatara Shanna Sasami Windancer Swanmay Wishsong Mamono Genewen Karo Zaitta Eecyla Adapt Iini Aisha Leda Gemini Aijimo Tama Nami
/set gk_alts=Aris Goodkind Somet Morsq Elvrysn Nonnus Esmarelda Mordsith Kor Vrodish Oreic Meder Iphonime Lolith Golrin Ugreth Syphon
/set gobo_alts=Gobo Wembley Fraggle Cantus
/set gor_alts=Matog Patog Gorion Sparticus Batog Spartucus Plvl Wakube
/set grazz_alts=Grazz Quenzil Carnage Slipshot Strafe Wynde Iceramandius Crag Trouble Kydrahl Traxx Daimos Ragee Johto Duecalion
/set jakk_alts=Cephas ClamBow FlamingIce Fused Jaihibairin Jakkbam JakkbamJr Jakky JClammer JClaw Jinx Joshua JrMint Lamdor Nihaomah Pocky Resonate ShadowClam Turbo
/set jaro_alts=Jaromil Laeh Jaeger Menelaus Allaq Salvation Silvius Versuchi Temujin Vang Hart Myo Lytor Zelich
/set jek_alts=AshA Eronak Feir Ganik Gengis Gouki Helfyre Iratavo JeKyll Kaboo Keiko Kromlee Mahal Maxine Muerte Paxon Phenyx Ronco Rygar Skia Tahn Tiati Verlegenheit Xurukk
/set manu_alts=Kaaria Manu Silvestre Tatewari Stars Citric Kukulc Elixis
/set mari_alts=Mari Kali Phalanx Delilah Elora Kontra Contra ReXMaN Brann Jaman Torment Nuthatch Poledra Melissa Demona Garwar Skate Garmag Aeri Ana Anakerie Catelyn
/set med_alts=Medic Kindle Clobber Rigby Vigil Vallta Scrivener Vorzak Camphor Swift Celestial Panzer
/set opp_alts=Bonez Oppresion Dez Dezor Rezod Nabliss Hyde Prowler Krakken Hoodwink Emyt Tyme Pips Tic Toc Tictoc Axiox Tyme Ygritte Bfh
/set peep_alts=Kubira Peep Masiah Heath
/set pyki_alts=Cheryomushki Baudolino Byki Emah Forseti Gautreau Gyki Haakon Hayami Khyfa Lasiter Ophallon Orcy Pyki Shouki Unky
/set raf_alts=Rafel Galomir Morgarach Grushnak
/set sansa_alts=Sansa Rhaella Syndane Mazzaroth Min Ripht Talmais
/set silv_alts=Naraku Xzibit Meista Serakis Silvanus Kikyo Siruh Ahrmin Duvessa Epyon Zodiac Atsiem
/set tange_alts=Tange Tundra Phi Kayln Dreya Mephista Atara Cloudchaser Matenda Mynara Quicken Terese Zerene Zarine Tiera
/set varewyr_alts=Alister Varewyr Zeroth
/set zaff_alts=Archnemesis Azurel Serric Zierlo Fierlo Lokken Melek Zaffer Helcaraxe Roger Sludge Rolodex Warierlo Delaznel Voxy Clr Imam Hierlo Xoom Jush Xharnah Zerric Zed Bodhisattva Rashomon Shaykh
/set zeek_alts=Zeek Zecastore Dracozeek Aznag Weez Zendrid Fleck Coss Buckey Gruff
/set zen_alts=Zen Kurtz Sever Othello Banquo Marlow Titus Pathos Iago Tuco Murdoch Lali Edgar Edward Keen Sanjuro Tsume Hubert Pazu Hiei Toguro Vance Aguirre Caspian Guts Olaf Barua Barub
/set anistra_alts=Anistra Stasia Yamine Lissa Anelise Nessa
