/set psi_abiku=boarquest
/set psi_aelaviirei=damage relief
/set psi_aff=dancing
/set psi_amn=amnwield amnoff
/set psi_annika=gator life
/set psi_arale=all.terror
/set psi_asmalal=void
/set psi_asha=all.pain
/set psi_atrocity=all.atrocity
/set psi_aurorie=aurorieoff auroriewield
/set psi_azuka=azukahit azukaoff
/set psi_baeron=blackspin
/set psi_banerae=banerae {15737}
/set psi_bolek=hitt retro
/set psi_boooored=bored
/set psi_bored=malice remorse
/set psi_brahma=fierc ragin
/set psi_brock=nightblade nine
/set psi_calp=calpchak32 calpchak2
/set psi_capulet=capuletwie capuletoff
/set psi_chiles=brock skillet 
/set psi_chloro=wildwood
/set psi_cognitive=devilgoat
/set psi_concertina=aria
/set psi_cruel=hitjf executioner
/set psi_deacon=deacon
/set psi_delaznel=croatoan delaznel
/set psi_diabolus=vermistra yxunomei
/set psi_dino=dino
/set psi_drakki=nyxx
/set psi_ebonkeir=ebonkeir
/set psi_elan=elanwield elanoffhand
/set psi_elowen=mace mace
/set psi_enaros=dingo laven
/set psi_eric=eric
/set psi_eshin=eshinsmight eshinoffhand
/set psi_essel=all.jorah
/set psi_fili=all.mungewield
/set psi_fnask=ormswield
/set psi_forseti=fleshslicer fleshrender
/set psi_freedman=maiming drooling
/set psi_frostie=apple
/set psi_galomir=avenger
/set psi_gerald=Vanquisher
/set psi_glamdring=narsil crunge
/set psi_gothmog=nightblade nine
/set psi_gravman=grav
/set psi_grizzdrop=all.hitt
/set psi_grizzlelumps=piercer
/set psi_gti=all.gti
/set psi_hierlo=damage
/set psi_hiram=hiram
/set psi_hoodwink=wink1 wink2
/set psi_huntley=roll ruin
/set psi_hydrosis=vinspi mommajebus
/set psi_image=bored remorse
/set psi_imamu=cuddles
/set psi_impending=terror impending2
/set psi_incarnado=hsword riviak
/set psi_interactive=erics
/set psi_ivrin=pain inform
/set psi_jaromil=aneurysm embolism
/set psi_jclaw=terror
/set psi_jinx=githyanki hitgear
/set psi_juvenia=acuity novaculite
/set psi_kali=apple
/set psi_kessler=hypera misoph
/set psi_kef=swirl
/set psi_kiron=purepain purepain
/set psi_koko=koko koko
/set psi_karanos=karawield karaoffhand
/set psi_krador=krador krador
/set psi_krak=kwhit krak
/set psi_language=mandelstick offhandstick
/set psi_lemmi=venom
/set psi_lycee=prism midnight
/set psi_maankashakt=ramuk maanka
/set psi_marwel=claw
/set psi_maxim=dual sky
/set psi_mazzaroth=needle
/set psi_meat=spectrah spectrah
/set psi_medea=Medea Lucidity
/set psi_meep=meep meep
/set psi_meista=meista
/set psi_merlen=merlen |br|merlen
/set psi_merple=peas broccoli
/set psi_message=medium voot
/set psi_mesmer=noetch
/set psi_methill=killl
/set psi_michelle=zenita natal
/set psi_mimi=destiny myzerie
/set psi_mindmelt=calris
/set psi_mithr=psiw rogo
/set psi_mosh=wield
/set psi_muaddib=spirit
/set psi_nit=waldorf
/set psi_nonaloth=nonawield nonaoffhand
/set psi_outcast=vanpsimain vanpsioff
/set psi_owari=all.ragn
/set psi_patog=mars thanatos
/set psi_pique=mental warped
/set psi_ponomariov=all.pono
/set psi_psychotia=psycho schizo
/set psi_pyriame=all.dreams
/set psi_ragnaros=lam psi
/set psi_rancor=malevolence extirpation
/set psi_raskaloth=reslae lizard
/set psi_riven=zzzz damage
/set psi_rol=rock roll
/set psi_ryethus=ryeoff stabstick
/set psi_selphie=hithit hellown
/set psi_shaft=qwert migraine
/set psi_shardik=tentacle1 tentacle2
/set psi_shanna=ciquala
/set psi_simayi=simayi simayi
/set psi_sirens bigaxe colmillo
/set psi_sisqo=duke duke
/set psi_skai=avenger
/set psi_sky=angel sword
/set psi_skyrift=skyswo skycola
/set psi_solack=ssssslithering pouncing
/set psi_somet=something something
/set psi_sorak=all.amagadon
/set psi_stan=boomerang
/set psi_starry=twinkling sparking
/set psi_sticks=pepper stix
/set psi_tavoli=tavclaw tavclaw
/set psi_terazen=all.terazen
/set psi_tida=finger stiletto
/set psi_tiffany=blood
/set psi_tingle=hitgear
/set psi_tossmeister=ooga booga
/set psi_tycho=baron
/set psi_uruloki=mars gorion
/set psi_walf=walf1 walfoff
/set psi_wizzle=broad
/set psi_woot=kesmai jomjeff
/set psi_vio=miw mio
/set psi_visete=nitram1 nitram2
/set psi_xalanth=cuddles
/set psi_xealot=all.ruby
/set psi_xialyn=guardian
/set psi_xwaldo=shim1 shim2
/set psi_yannet=yan yan
/set psi_yus=fear
/set psi_zaitta=prism twilight
/set psi_zarradyn=all.hitt
/set psi_zeal=heaven krak2
