/set ac_bag "floating icesphere tankgear"

/set ac_light "stone flame inferno"
/set ac_finger1 "water ring"
/set ac_finger2 "ring earth elemental lordgear"
/set ac_neck1 "black scarf pitch lordgear"
/set ac_neck2 "black scarf pitch lordgear"
/set ac_body "moon priestess garb"
/set ac_head "helm githyanki silver gith"
/set ac_legs "living dark mystical daemonstone"
/set ac_feet "boots conquerer lordgear"
/set ac_hands "gauntlets protection"
/set ac_arms "billowing sleeves of vapor wind"
/set ac_offhand "the Shield of Lords pitch black lordgear"
/set ac_about "stone wings lordgear"
/set ac_waist "red cotton belt lordgear gorn"
/set ac_wrist1 "kzinti kzintium blade bracer"
/set ac_wrist2 "kzinti kzintium blade bracer"
/set ac_wield "huge red eye oni bloodshot"
/set ac_held "lodestone chunk rock"
