/set hit_bag "urn black roghit2"

/set hit_light "eria sceptre"
/set hit_finger1 "ice ring"
/set hit_finger2 "ice ring"
/set hit_neck1 "necklace teeth"
/set hit_neck2 "necklace teeth"
/set hit_body "ultimoose"
/set hit_head "helm cherubims"
/set hit_feet "heroic dragonscale slippers"
/set hit_legs "gator scaled breeches"
/set hit_hands "killing gloves"
/set hit_arms "dwarven dark brand"
/set hit_offhand "dagger flame shaped dosdagger"
/set hit_about "deathshroud"
/set hit_waist "steel collar"
/set hit_wrist1 "scorpion tattoo picture"
/set hit_wrist2 "scorpion tattoo picture"
/set hit_wield "dagger flame shaped unodagger"
/set hit_held "doom marble shard"
