; hero.hit4.ava.tf

/set hit_bag "bodybag body bag hitgear!" 

/set hit_light "eria sceptre silver glowing eye"
/set hit_finger1 "an ice ring"
/set hit_finger2 "an ice ring"
/set hit_neck1 "medallion justice"
/set hit_neck2 "medallion justice"
/set hit_body "silver breast plate"
/set hit_head "helm cherubims"
/set hit_legs "pants flaming"
/set hit_feet "fatewalkers mystical sandals"
/set hit_hands "killing gloves"
/set hit_arms "dragon tattoo glimmer"
/set hit_offhand "dragon bone blade sword"
/set hit_about "robe greatness"
/set hit_waist "steel collar"
/set hit_wrist1 "scorpion tattoo picture"
/set hit_wrist2 "scorpion tattoo picture"
/set hit_wield "sword baron"
/set hit_held "essence amorphous orb"
