/set ac_bag "bodybag body bag eviltank"

/set ac_light "stone flame"
/set ac_finger1 "anthanrian ring"
/set ac_finger2 "anthanrian ring"
;/set ac_neck1 "carved bone necklace"
/set ac_neck1 "fingerbone kra"
/set ac_neck2 "amulet turtle shell"
/set ac_body "embroidered chestplate"
/set ac_head "teardrop helm"
/set ac_legs "heroic dragonscale skirt"
/set ac_feet "sandal fatewalker"
/set ac_hands "archer gauntlet"
/set ac_arms "steel bracer"
/set ac_offhand "hero shield"
/set ac_about "unholy shroud"
/set ac_waist "steel collar"
/set ac_wrist1 "nagaskin"
/set ac_wrist2 "nagaskin"
/set ac_wield "saber"
/set ac_held "leman seal"
