/set hit_bag "urn black"

/set hit_light "eria sceptre hitt"
/set hit_finger1 "ice ring hitt"
/set hit_finger2 "ice ring hitt"
/set hit_neck1 "necklace teeth hitt"
/set hit_neck2 "necklace teeth hitt"
/set hit_body "ultimoose hitt"
/set hit_head "helm cherubims hitt"
/set hit_legs "pants flaming hitt"
/set hit_feet "fatewalk hitt"
/set hit_hands "killing gloves hitt"
/set hit_arms "spiked sleeves hitt"
/set hit_offhand "nephilim blade ethereal"
/set hit_about "deathshroud hitt"
/set hit_waist "steel collar hitt"
/set hit_wrist1 "scorpion tattoo picture hitt"
/set hit_wrist2 "scorpion tattoo picture hitt"
/set hit_wield "tourach sword gash"
/set hit_held "doom marble shard hitt"
