/set ac_bag "bodybag body bag tank"
/set ac_light "stone flame"
/set ac_finger1 "quest ring"
/set ac_finger2 "quest ring"
/set ac_neck1 "carved bone necklace"
/set ac_neck2 "carved bone necklace"
/set ac_body "carborized steel armor"
/set ac_head "smoldering crown"
/set ac_legs "heroic dragonscale skirt"
/set ac_feet "sandal fatewalker"
/set ac_hands "archer gauntlet"
/set ac_arms "steel bracer"
/set ac_offhand "hero shield fire"
/set ac_about "unholy shroud"
/set ac_waist "steel collar"
/set ac_wrist1 "dark rune kra"
/set ac_wrist2 "dark rune kra"
/set ac_wield "bladed shield"
/set ac_held "leman seal"
