; hero.ac2.gear.ava.tf

/set ac_bag "bodybag body bag tankgear"

/set ac_light "orb shogun pearl sceptre"
/set ac_finger1 "Antharian Signet ring"
/set ac_finger2 "Antharian Signet ring"
/set ac_neck1 "carved bone necklace"
/set ac_neck2 "carved bone necklace"
/set ac_body "carburized steel plate armor"
/set ac_head "teardrop helmet"
/set ac_legs "heroic dragonscale dragon scale skirt pants"
/set ac_feet "fatewalkers mystical sandals"
/set ac_hands "single silver archer's gauntlet"
/set ac_arms "steel bracers"
/set ac_offhand "hero heroes shield tank woe"
/set ac_about "shroud cloth unholy"
/set ac_waist "collar steel chained"
/set ac_wrist1 "dark rune kra"
/set ac_wrist2 "dark rune kra"
/set ac_wield "bladed shield silver"
/set ac_held "lemans family seal talisman"
