/set mana_bag "jumpsuit white manastuff"
/set mana_light "glimmer hellfire"
/set mana_finger1 "strand haghair hair"
/set mana_finger2 "strand haghair hair"
/set mana_neck1 "cape angel feathers"
/set mana_neck2 "cape angel feathers"
/set mana_body "white leather dress"
/set mana_head "crown ages"
/set mana_legs "waterlace leggings"
/set mana_feet "toe ring"
/set mana_hands "watershape blob water"
/set mana_arms "silver armlet iguana"
/set mana_offhand "staff ancient magicks"
/set mana_about "nethershroud hole black despair"
/set mana_waist "belt sorcery"
/set mana_wrist1 "jade bracer"
/set mana_wrist2 "jade bracer"
/set mana_wield "staff ancient magicks"
/set mana_held "chalice head lord"

