/set ac_bag "floating icesphere tankgear"

/set ac_light "glimmering shard starshard starshine"
/set ac_finger1 "water ring"
/set ac_finger2 "water ring"
/set ac_neck1 "ruling glyph fae lordgear rune"
/set ac_neck2 "ruling glyph fae lordgear rune"
/set ac_body "armor ornate silver githyanki gith chestplate lordgear"
/set ac_head "jeweled crown aziz-ra"
/set ac_legs "living dark mystical daemonstone"
/set ac_feet "boots conquerer lordgear"
/set ac_hands "zarradyn's gauntlets lordgear"
/set ac_arms "black armband lordgear tank"
/set ac_offhand "great shield tyranny lordgear"
/set ac_about "stone wings lordgear"
/set ac_waist "gold belly chain"
/set ac_wrist1 "kzinti kzintium blade bracer"
/set ac_wrist2 "kzinti kzintium blade bracer"
/set ac_wield "huge red eye oni bloodshot"
/set ac_held "lodestone chunk rock"
