/set ac_bag "bodybag body bag acgearz"

/set ac_light "glimmering shard starshard starshine"
/set ac_finger1 "water ring"
/set ac_finger2 "water ring"
/set ac_neck1 "ruling glyph fae lordgear rune"
/set ac_neck2 "ruling glyph fae lordgear rune"
/set ac_body "armor ornate silver githyanki gith chestplate"
/set ac_head "helm githyanki silver gith"
/set ac_legs "living dark mystical daemonstone"
/set ac_feet "boots conquerer lordgear"
/set ac_hands "zarradyn's gauntlets"
/set ac_arms "black armband"
/set ac_offhand "huge red eye oni bloodshot"
/set ac_about "shimmering grey cloak"
/set ac_waist "gold belly chain"
/set ac_wrist1 "kzinti kzintium blade bracer"
/set ac_wrist2 "kzinti kzintium blade bracer"
/set ac_wield "gray staff"
/set ac_held "lodestone chunk rock"
