; lord.ac2.ava.tf
; Insured to: Gengis
/set ac_bag "bodybag body bag acgearz"

/set ac_light "stone flame inferno"
/set ac_finger1 "ring earth elemental"
/set ac_finger2 "ring earth elemental"
/set ac_neck1 "ruling glyph fae"
/set ac_neck2 "ruling glyph fae"
/set ac_body "armor ornate silver githyanki gith chestplate"
/set ac_head "helm githyanki silver gith"
/set ac_legs "living dark mystical daemonstone"
/set ac_feet "boots righteous path"
/set ac_hands "zarradyn's gauntlets"
/set ac_arms "black armband"
/set ac_offhand "shield tyranny"
/set ac_about "stone wings"
/set ac_waist "crimson bloodsash"
/set ac_wrist1 "kzinti kzintium blade bracer"
/set ac_wrist2 "kzinti kzintium blade bracer"
/set ac_wield "emeral longsword"
/set ac_held "lodestone chunk rock"
