/set ac_bag "bodybag body bag acgearz"
/set ac_light "stone flame inferno"
/set ac_finger1 "water ring"
/set ac_finger2 "water ring"
/set ac_neck1 "black scarf pitch lordgear"
/set ac_neck2 "black scarf pitch lordgear"
/set ac_body "armor ornate silver githyanki gith chestplate"
/set ac_head "helm githyanki silver gith"
/set ac_legs "living dark mystical daemonstone"
/set ac_feet "boots conquerer lordgear"
/set ac_hands "zarradyn's gauntlets"
/set ac_arms "black armband"
/set ac_offhand "shield tyranny"
/set ac_about "stone wings lordgear"
/set ac_waist "red cotton belt lordgear gorn"
/set ac_wrist1 "kzinti kzintium blade bracer"
/set ac_wrist2 "kzinti kzintium blade bracer"
/set ac_wield "gray staff"
/set ac_held "lodestone chunk rock"
