; lord.ac1.ava.tf

/set ac_bag "shaft skin bag"

/set ac_light "sphere burning souls"
/set ac_finger1 "ring earth elemental lordgear"
/set ac_finger2 "ring earth elemental lordgear"
/set ac_neck1 "ruling glyph fae"
/set ac_neck2 "ruling glyph fae"
/set ac_body "emblazoned armor ironhand lordgear"
/set ac_head "hood ferrets lordgear"
/set ac_legs "living dark mystical daemonstone"
/set ac_feet "boots righteous path"
/set ac_hands "zarradyn's gauntlets"
/set ac_arms "black armband"
/set ac_offhand "great shield tyranny lordgear"
/set ac_about "stone wings"
/set ac_waist "crimson bloodsash"
/set ac_wrist1 "kzinti kzintium blade bracer"
/set ac_wrist2 "kzinti kzintium blade bracer"
/set ac_wield "public approval"
/set ac_held "lodestone chunk rock"
