/set hit_bag "urn black hitgear"

/set hit_light "sceptre blazing fury"
/set hit_finger1 "ring higher power"
/set hit_finger2 "ring higher power"
/set hit_neck1 "necklace severed fae ears"
/set hit_neck2 "necklace severed fae ears"
/set hit_body "tuatar battle tunic loose gi"
/set hit_head "crown pain wire shards glass"
/set hit_legs "living dark mystical daemonstone"
/set hit_feet "boots planewalking mithril"
/set hit_hands "zarradyn's gauntlets"
/set hit_arms "watermark tattoo wave"
/set hit_offhand "kzinti commander claw lordgear"
/set hit_about "cloud dancing shards glass"
/set hit_waist "belt souls strap"
/set hit_wrist1 "broken shackles tyranny"
/set hit_wrist2 "broken shackles tyranny"
/set hit_wield "sword githyanki gith silver lordgear normal"
/set hit_held "doom shard"
