/set det_bag "floating icesphere detgear!"

/set det_light "sphere burning souls"
/set det_finger1 ""
/set det_finger2 ""
/set det_neck1 "ice collar"
/set det_neck2 "ice collar"
/set det_body ""
/set det_head ""
/set det_legs ""
/set det_feet ""
/set det_hands ""
/set det_arms ""
/set det_offhand "shield tyranny"
/set det_about "stone wings"
/set det_waist "crimson bloodsash"
/set det_wrist1 "kzinti kzintium blade bracer"
/set det_wrist2 ""
/set det_wield "bladed shield silver"
/set det_held "basilisk field"
